# Pipeline utilisé par les enseignant
# 
# Sert à automatiser le déploiment continue des applications vers le cluster Kubernetes
name: Generate ZIP - Week 5

on:
  workflow_dispatch:

jobs:

  call-workflow-generate-zip-for-students:
    uses: 420-2w6-em/devops-pipelines/.github/workflows/generate_zips_for_week_and_commit-2w6.yml@main
    with:
      CONFIG_FILENAME_FOR_THE_WEEK: "configuration-week5-r09-r10.json"
    secrets: inherit