# Pipeline utilisé par les enseignant
# 
# Sert à automatiser le déploiment continue des applications vers le cluster Kubernetes
name: CI/CD Pipeline

on:
  push:             # Pipeline trigger lors d'un commit sur les branches du projets en suivant le standard GitFlow
    branches: 
      - main        # Branche principale

jobs:

  generate_zips_for_week : 
    runs-on: self-hosted   # Agent onprem à même le cluster Kubernetes pour réaliser l'exécution du build (machine linux)
    
    steps:
    #- name: Checkout code
    #  uses: actions/checkout@v4

    - name: Configurer Git
      run: |
        git config --global user.name 'gitHub actions runner'
        git config --global user.email 'runner@4202w6.com'

    - name: Setup python and run script
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install gitpython

    - name: Run Python script
      run: |
        git clone https://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@github.com/420-2W6-EM/generate_zip.git
        source venv/bin/activate
        python -u generate-zips-for-week.py configuration-fichier-r01-r02.json
        ls
        cd zip-generated
        ls
        cd ../output
        ls
        cd ..
        find output -maxdepth 1 -type f -name "*.zip" -exec cp {} zip-generated \;
        cd zip-generated
        ls
        git add .
        git commit -m "Generate zips for week"
        git push
     # env:
     #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
